# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3482136c5db3d16ba30b19de6f68c0c398175b5defb05436938fcece2f7193846ec40f6fc86be42a9a1bf1c6516b12a83bd33438f7a781ee3420ac0f73d529f5

test:
  secret_key_base: b3b0a9c0f3b1d23c2a1d9459eda4e49543313908f571ae1fdacb1c3764c42ea2614ab15591c885b227e72c07445c805bd94963126ba920e9f68c222605cd2abd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
